set(CTEST_PROJECT_NAME "libpng")
set(CTEST_BUILD_NAME "$ENV{SGEN}-libpng")
set(CTEST_SITE "$ENV{COMPUTERNAME}")

set(VER "$ENV{LIBPNG_VER}")
set(CTEST_SOURCE_DIRECTORY "${CTEST_SCRIPT_DIRECTORY}/lib/src/libpng-${VER}")
set(CTEST_BINARY_DIRECTORY "${CTEST_SCRIPT_DIRECTORY}/lib/build/libpng-${VER}/${CONF_DIR}")

set(BUILD_OPTIONS
  -DCMAKE_INSTALL_PREFIX:PATH=${CTEST_SCRIPT_DIRECTORY}/lib/install/libpng-${VER}/${CONF_DIR}
  -DZLIB_INCLUDE_DIR:PATH=${CTEST_SCRIPT_DIRECTORY}/lib/install/hdf5-$ENV{HDF5_VER}/${CONF_DIR}/include
)

if("${CONF_DIR}" STREQUAL "debug")
  list(APPEND BUILD_OPTIONS "-DZLIB_LIBRARY:PATH=${CTEST_SCRIPT_DIRECTORY}/lib/install/hdf5-$ENV{HDF5_VER}/${CONF_DIR}/lib/zlib_D.lib")
else()
  list(APPEND BUILD_OPTIONS "-DZLIB_LIBRARY:PATH=${CTEST_SCRIPT_DIRECTORY}/lib/install/hdf5-$ENV{HDF5_VER}/${CONF_DIR}/lib/zlib.lib")
endif()

CTEST_START("Experimental")
CTEST_CONFIGURE(BUILD "${CTEST_BINARY_DIRECTORY}"
                OPTIONS "${BUILD_OPTIONS}")
CTEST_BUILD(BUILD "${CTEST_BINARY_DIRECTORY}")
CTEST_BUILD(BUILD "${CTEST_BINARY_DIRECTORY}" TARGET install)
