set(CTEST_PROJECT_NAME "expat")
set(CTEST_BUILD_NAME "$ENV{SGEN}-expat")
set(CTEST_SITE "$ENV{COMPUTERNAME}")

set(VER "$ENV{EXPAT_VER}")
set(CTEST_SOURCE_DIRECTORY "${CTEST_SCRIPT_DIRECTORY}/lib/src/expat-${VER}/expat")
set(CTEST_BINARY_DIRECTORY "${CTEST_SCRIPT_DIRECTORY}/lib/build/expat-${VER}")

set(BUILD_OPTIONS
  -DCMAKE_INSTALL_PREFIX:PATH=${CTEST_SCRIPT_DIRECTORY}/lib/install/expat-${VER}/${CONF_DIR}
  -DBUILD_tools:BOOL=$ENV{BUILD_TOOLS}
)

CTEST_START("Experimental")
CTEST_CONFIGURE(BUILD "${CTEST_BINARY_DIRECTORY}"
                OPTIONS "${BUILD_OPTIONS}")
CTEST_BUILD(BUILD "${CTEST_BINARY_DIRECTORY}")
CTEST_BUILD(BUILD "${CTEST_BINARY_DIRECTORY}" TARGET install)
