set(CTEST_PROJECT_NAME "poco")
set(CTEST_BUILD_NAME "$ENV{SGEN}-${CTEST_PROJECT_NAME}")
set(CTEST_SITE "$ENV{COMPUTERNAME}")

set(VER "$ENV{POCO_VER}")

set(BUILD_OPTIONS 
"-DCMAKE_INSTALL_PREFIX:PATH=${CTEST_SCRIPT_DIRECTORY}/lib/install/${CTEST_PROJECT_NAME}-${VER}"
)

CTEST_START("Experimental")
CTEST_CONFIGURE(BUILD "${CTEST_BINARY_DIRECTORY}"
                OPTIONS "${BUILD_OPTIONS}")
CTEST_BUILD(BUILD "${CTEST_BINARY_DIRECTORY}")
CTEST_BUILD(BUILD "${CTEST_BINARY_DIRECTORY}" TARGET install)
